### PR TITLE
Test container

### PR DESCRIPTION
**Pull request by iTchTheRightSpot**
So you know your secrets are public but below are the list of changes I made

1. Added test container to simplify local development. Note Docker will be needed to pull PostgreSQL image
2. Removed unnecessary `maven-compiler-plugin` in pom file 
3. Refactor logging behaviour in application.properties

### CODE REVIEW

**Comment by tcudjoe** [comment]
???

**Comment by iTchTheRightSpot** [comment]
Contributing to your issue from amigos discord

**Comment by tcudjoe** [comment]
Amigos discord? I’m not sure I reside in there. I recently joined Alibou coding server if thats what you mean?

**Comment by iTchTheRightSpot** [comment]
I just double checked you are right. Alibou

**Comment by tcudjoe** [comment]
Right! But I think I mentioned I got it fixed, what exactly did you improve?

**Comment by iTchTheRightSpot** [comment]
Mainly wanted to test forking and opening a pull request but these are the improvements I made:-

- Added test container to simplify local development. Note Docker will be needed to pull PostgreSQL image
- Removed unnecessary maven-compiler-plugin in pom file
- Refactor logging behaviour in application.properties

**Pull request closed without merging**
